import { GoogleGenAI, Modality, GenerateContentResponse } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  console.error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

const dataUrlToBase64 = (dataUrl: string): string => {
  return dataUrl.includes(',') ? dataUrl.split(',')[1] : dataUrl;
};

export const generateImage = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  try {
    const imagePart = {
      inlineData: {
        data: dataUrlToBase64(base64Image),
        mimeType: mimeType,
      },
    };

    const textPart = {
      text: prompt,
    };

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [{
        parts: [imagePart, textPart],
      }],
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });
    
    if (response.promptFeedback?.blockReason) {
      throw new Error(`Request blocked due to: ${response.promptFeedback.blockReason}.`);
    }

    const candidate = response.candidates?.[0];

    if (!candidate) {
      const blockReason = response.promptFeedback?.blockReason ?? 'Unknown reason';
      throw new Error(`API returned no candidates. This may be due to a safety block (${blockReason}).`);
    }
    
    if (candidate.finishReason && candidate.finishReason !== 'STOP') {
      throw new Error(`Generation stopped for reason: ${candidate.finishReason}.`);
    }

    for (const part of candidate.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }

    const textResponse = response.text?.trim();
    if (textResponse) {
        throw new Error(`No image was generated. API returned text: "${textResponse}"`);
    }

    throw new Error("No image was generated by the API, and no other errors were reported.");

  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    const errorMessage = (error as Error).message || "Unknown API error";
    
    if (errorMessage.toLowerCase().includes("blocked") || errorMessage.toLowerCase().includes("safety")) {
        throw new Error(`Blocked by safety filter. Reason: ${errorMessage}`);
    }
    
    throw new Error(`API Error: ${errorMessage}`);
  }
};